config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :subscriptions
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :blogs
  resources :abouts
  resources :contacts
  resources :internships
  resources :organisations
  resources :homes

  root 'homes#index'
end

app/models/blog.rb
# frozen_string_literal: true

class Blog < ApplicationRecord
  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true

  has_attached_file :image, styles: { medium: '300x300>', thumb: '100x100>' }
  validates_attachment_content_type :image, content_type: %r{\Aimage/.*\z}
end

app/controllers/blogs_controller.rb
# frozen_string_literal: true

class BlogsController < ApplicationController
  before_action :set_blog, only: %i[show edit update destroy]

  def index
    @pagy, @blogs = pagy(Blog.all.order('created_at DESC'), items: 3)
    @search = params['search']

    if @search.present?
      @title = @search['title']
      @blogs = Blog.where('title ILIKE ?', "%#{@title}%")
    end
  end

  def show
    @blog = Blog.find(params[:id])
    @blogs = Blog.order('created_at desc')
  end

  def new
    @blog = Blog.new
  end

  def edit; end

  def create
    @blog = Blog.new(blog_params)

    respond_to do |format|
      if @blog.save
        format.html { redirect_to @blog, notice: 'Blog was successfully created.' }
        format.json { render :show, status: :created, location: @blog }
      else
        format.html { render :new }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @blog.update(blog_params)
        format.html { redirect_to @blog, notice: 'Blog was successfully updated.' }
        format.json { render :show, status: :ok, location: @blog }
      else
        format.html { render :edit }
        format.json { render json: @blog.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @blog.destroy
    respond_to do |format|
      format.html { redirect_to blogs_url, notice: 'Blog was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_blog
    @blog = Blog.find(params[:id])
  end

  def blog_params
    params.require(:blog).permit(:title, :body)
  end
end

app/helpers/blogs_helper.rb
# frozen_string_literal: true

module BlogsHelper
end

app/views/blogs/_form.html.erb
<%= form_with(model: blog, local: true) do |form| %>
  <% if blog.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(blog.errors.count, "error") %> prohibited this blog from being saved:</h2>

      <ul>
      <% blog.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/blogs/edit.html.erb
<h1>Editing Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Show', @blog %> |
<%= link_to 'Back', blogs_path %>

app/views/blogs/index.html.erb
<!--
|========================
|      Features Section
|========================
-->
<section class="uv-subpage-heading image-bg" style="background-image: url('assets/header-bg-1.jpg');">
  <div class="overlay">
    <div class="container">
      <div class="row">
        <div class="uv-subhead-content col-xs-12">
          <h2>Blog & News </h2>
          <span><%= Time.now %></span>
        </div>
      </div>
    </div>
  </div>
</section>

<div class="uv-pagination">
  <div class="container">
    <ul>
      <li class="active"><a href="">Home</a></li>
      <li><a href="">Blog</a></li>
    </ul>
  </div>
</div>

<section class="uv-single-blog">
  <div class="container">
    <div class="row section-separator">
      <div class="col-sm-8">
        <div class="blog-wrapper shadow-border single-blog-wrapper">
          <% @blogs.each do |blog| %>
            <tr>
              <div class="blog-title">
                <td><h2><%= blog.title %></h2></td>
                <div class="post-meta">
                  <span class="day">Created At: <%= blog.created_at %></span>
                  <span class="month">Updated At: <%= blog.updated_at %></span>
                </div>
              </div>

              <div class="blog-image">
                <%= link_to blog.image.url do %>
                  <%= image_tag blog.image.url, class: "img-responsive" %>
                <% end %>
              </div>
              <div class="blog-desc">
                <td><p><%= blog.body %></p></td>
                <a href="#" class="readmore">Read More</a>
              </div>
            </tr>
          <% end %>
        </div>

        <div class="uv_pagination_outer_wrap">
          <ul>
            <i><%= pagy_bootstrap_nav(@pagy).html_safe %></i>
          </ul>
        </div>

      </div>

      <aside class="uv-sidebar col-md-3 col-sm-12">
        <div class="uv_aside_hdg default_width mb30">
          <%= simple_form_for :search, url: blogs_path, method: "GET", html: { class: 'form-inline' } do |f| %>
            <h6>Find Blogs</h6>
            <i class="fa fa-minus"></i>
            <form lpformnum="1">
              <div class="uv_aside_field">
                <%= f.input :title, placeholder: "Search by key word here...", input_html: {value: ""} %>
              </div>
              <div class="uv_aside_field">
                <%= f.submit "Search", class: "btn btn-fill btn-block" %>
              </div>
            </form>
          <% end %>
        </div>
       
        <div class="clearfix"></div>
          <div class="uv-widget">
            <div class="widget-title">
              <h4>Subscribe Us</h4>
              <hr>
            </div>
            <div class="uv-newsletter">
              <p>Subscribe to our weekly Newsletter and stay up to date.</p>
              <form lpformnum="3" _lpchecked="1">
                <a href="subscriptions"><i class="btn btn-fill btn-block">Subscribe Now!</i></a>
              </form>
            </div>
          </div>
        </div>

      </aside>

    </div>
  </div>
</section>

app/views/blogs/new.html.erb
<h1>New Blog</h1>

<%= render 'form', blog: @blog %>

<%= link_to 'Back', blogs_path %>

app/views/blogs/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @blog.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @blog.body %>
</p>

<%= link_to 'Edit', edit_blog_path(@blog) %> |
<%= link_to 'Back', blogs_path %>