config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :subscriptions
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :blogs
  resources :abouts
  resources :contacts
  resources :internships
  resources :organisations
  resources :homes

  root 'homes#index'
end

app/models/organisation.rb
# frozen_string_literal: true

class Organisation < ApplicationRecord
  has_many :internships, dependent: :destroy

  validates :category, presence: true
  validates :name, presence: true
  validates :body, presence: true

  has_attached_file :image, styles: { medium: '300x300>', thumb: '100x100>' }
  validates_attachment_content_type :image, content_type: %r{\Aimage/.*\z}
end

app/controllers/organisations_controller.rb
# frozen_string_literal: true

class OrganisationsController < ApplicationController
  before_action :set_organisation, only: %i[show edit update destroy]

  def index
    @pagy, @organisations = pagy(Organisation.all.order('created_at DESC'), items: 3)
    @search = params['search']

    if @search.present?
      @category = @search['category']
      @organisations = Organisation.where('category ILIKE ?', "%#{@category}%")
    end
  end

  def show
    @organisation = Organisation.find(params[:id])
    @organisations = Organisation.order('created_at desc')
  end

  def new
    @organisation = Organisation.new
  end

  def edit; end

  def create
    @organisation = Organisation.new(organisation_params)

    respond_to do |format|
      if @organisation.save
        format.html { redirect_to @organisation, notice: 'Organisation was successfully created.' }
        format.json { render :show, status: :created, location: @organisation }
      else
        format.html { render :new }
        format.json { render json: @organisation.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @organisation.update(organisation_params)
        format.html { redirect_to @organisation, notice: 'Organisation was successfully updated.' }
        format.json { render :show, status: :ok, location: @organisation }
      else
        format.html { render :edit }
        format.json { render json: @organisation.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @organisation.destroy
    respond_to do |format|
      format.html { redirect_to organisations_url, notice: 'Organisation was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_organisation
    @organisation = Organisation.find(params[:id])
  end

  def organisation_params
    params.require(:organisation).permit(:category, :name, :body)
  end
end

app/helpers/organisations_helper.rb
# frozen_string_literal: true

module OrganisationsHelper
end

app/views/organisations/_form.html.erb
<%= form_with(model: organisation, local: true) do |form| %>
  <% if organisation.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(organisation.errors.count, "error") %> prohibited this organisation from being saved:</h2>

      <ul>
      <% organisation.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/organisations/edit.html.erb
<h1>Editing Organisation</h1>

<%= render 'form', organisation: @organisation %>

<%= link_to 'Show', @organisation %> |
<%= link_to 'Back', organisations_path %>

app/views/organisations/index.html.erb
<!--
|========================
| Organisation Section
|========================
-->
<section class="uv-subpage-heading image-bg" style="background-image: url('assets/header-bg-1.jpg');">
  <div class="overlay">
    <div class="container">
      <div class="row">
        <div class="uv-subhead-content col-xs-12">
          <h2>Organisations</h2>
          <span><%= Time.now %></span>
        </div>
      </div>
    </div>
  </div>
</section>

<div class="uv-pagination">
  <div class="container">
    <ul>
      <li><b>Home</b></li>
      <li><i>Organizations</i></li>
    </ul>
  </div>
</div>

<section class="uv-single-blog">

  <div class="container">
    <div class="row section-separator">

      <div class="col-sm-8">
        <div class="blog-wrapper shadow-border single-blog-wrapper">
          <tr>
            <div class="col-xs-12">
              <div id="integration-list-2" class="uv-accordinaton">
                <ol>
                  <li>
                    <% @organisations.each do |organisation| %>
                    <a class="uv-accordinaton-list">
                    <div class="uv-right-arrow">+</div>
                      <h6><u><b><%= organisation.id %>. Category:</b> <%= organisation.category %></u></h6>
                      <h2>Name:<%= organisation.name %></h2>
                      <i><b>(Show More/Less)</b></i>
                    </a>
                    <div class="uv-accordition-detail">
                      <%= link_to organisation.image.url do %>
                        <%= image_tag organisation.image.url, class: "img-responsive" %>
                      <% end %>

                      <p><%= organisation.body %></p>
                      <a href="internships" class="btn btn-fill">See Open Internships</a>
                    </div>
                    <% end %>
                  </li>
                </ol>
              </div>
            </div>
          </tr>
        </div>

        <div class="uv_pagination_outer_wrap">
          <ul>
            <i><%= pagy_bootstrap_nav(@pagy).html_safe %></i>
          </ul>
        </div>

      </div>

      <div class="uv-single-contest uv-course-details">
        <div class="container">
          <div class="educationpress-main-content-inner row">

            <aside class="uv-sidebar col-md-3 col-sm-12">
              <div class="uv_aside_hdg default_width mb30">
                <%= simple_form_for :search, url: organisations_path, method: "GET", html: { class: 'form-inline' } do |f| %>
                  <h6>Find Organisations</h6>
                  <i class="fa fa-minus"></i>
                  <form lpformnum="1">
                    <div class="uv_aside_field">
                      <%= f.input :category, placeholder: "Search by key word here...", input_html: {value: ""} %>
                    </div>
                    <div class="uv_aside_field">
                      <%= f.submit "Search", class: "btn btn-fill btn-block" %>
                    </div>
                  </form>
                <% end %>
              </div>
             
              <div class="clearfix"></div>
                <div class="uv-widget">
                  <div class="widget-title">
                    <h4>Subscribe Us</h4>
                    <hr>
                  </div>
                  <div class="uv-newsletter">
                    <p>Subscribe to our weekly Newsletter and stay up to date.</p>
                    <form lpformnum="3" _lpchecked="1">
                      <a href="subscriptions"><i class="btn btn-fill btn-block">Subscribe Now!</i></a>
                    </form>
                  </div>
                </div>
              </div>

            </aside>

          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section class="uv-our-clients">
  <div class="container">
    <div class="row section-separator">
      <div class="col-xs-12 center section-title">
        <h2>Our Clients</h2>
      </div>
      <div class="clients-logos">
        <div class="col-md-2 col-sm-4">
          <i class='fas fa-laptop' style='font-size:80px;color:darkblue'><h5>Software Companies</h5></i>
        </div>
        <div class="col-md-2 col-sm-4">
          <i class='fas fa-hotel' style='font-size:80px;color:darkgreen'><h5>Hotels & Restaurant</h5></i>
        </div>
        <div class="col-md-2 col-sm-4">
          <i class='fas fa-school' style='font-size:80px;color:grey'><h5>Schools</h5></i>
        </div>
        <div class="col-md-2 col-sm-4">
          <i class='fas fa-hospital' style='font-size:80px;color:purple'><h5>Hospitals</h5></i>
        </div>
        <div class="col-md-2 col-sm-4">
          <i class='fas fa-satellite-dish' style='font-size:80px;color:maroon'><h5>Media Stations</h5></i>
        </div>
        <div class="col-md-2 col-sm-4">
          <i class='fas fa-sim-card' style='font-size:80px;color:indigo'><h5>Telecommunication Companies</h5></i>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/organisations/new.html.erb
<h1>New Organisation</h1>

<%= render 'form', organisation: @organisation %>

<%= link_to 'Back', organisations_path %>

app/views/organisations/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @organisation.category %>
</p>

<p>
  <strong>Name:</strong>
  <%= @organisation.name %>
</p>

<p>
  <strong>Body:</strong>
  <%= @organisation.body %>
</p>

<%= link_to 'Edit', edit_organisation_path(@organisation) %> |
<%= link_to 'Back', organisations_path %>