config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :subscriptions
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :blogs
  resources :abouts
  resources :contacts
  resources :internships
  resources :organisations
  resources :homes

  root 'homes#index'
end

app/models/subscription.rb
# frozen_string_literal: true

class Subscription < ApplicationRecord
  validates :email, presence: true, uniqueness: true
  validates_format_of :email, with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\Z/i, on: :create
end

app/controllers/subscriptions_controller.rb
# frozen_string_literal: true

class SubscriptionsController < InheritedResources::Base
  before_action :set_subscription, only: %i[show edit update destroy]

  def index
    @subscriptions = Subscription.all
  end

  def new
    @subscription = Subscription.new
  end

  def create
    @subscription = Subscription.new(subscription_params)

    respond_to do |format|
      if @subscription.save
        format.html do
          flash[:success] = 'Subscribed!'
          redirect_to subscriptions_url
        end
      else
        format.html { flash[:failure!] = 'Not Subscribed! Verify Details & Try Again!' }
        format.html { render 'new' }
      end
    end
  end

  private

  def set_contact
    @subscription = Subscription.find(params[:id])
  end

  def subscription_params
    params.require(:subscription).permit(:email)
  end
end

app/helpers/subscriptions_helper.rb
# frozen_string_literal: true

module SubscriptionsHelper
end

app/views/subscriptions/_form.html.erb
<%= simple_form_for(@subscription) do |f| %>
  <%= f.error_notification %>
  <%= f.error_notification message: f.object.errors[:base].to_sentence if f.object.errors[:base].present? %>

  <div class="form-inputs">
    <%= f.input :email %>
  </div>

  <div class="form-actions">
    <%= f.button :submit %>
  </div>
<% end %>

app/views/subscriptions/edit.html.erb
<h1>Editing Subscription</h1>

<%= render 'form', subscription: @subscription %>

<%= link_to 'Show', @subscription %> |
<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/index.html.erb
<section class="uv-contact">
    <div class="container">
        <div class="row section-separator">
            <div class="col-md-9 col-sm-12 col-xs-12 content-widget">
                <div class="col-xs-12 widget-title">
                    <h4>Subscribe To Us Now!</h4>
                    <hr class="uv-hr">
                </div>

                <%= form_for Subscription.new, url: {action: "create"}, html: {class: "single-form quate-form"} do |f| %>
                  <div id="msgSubmit" class="h3 text-center hidden"></div>
                  <div class="col-md-4">
                    <p>Subscribe to our weekly Newsletter and stay tuned and stay up to date!</p>
                  </div>
                  <div class="col-sm-12 col-md-8">
                    <%= f.text_field :email, placeholder: 'Enter your email here...', class: 'contact-subject form-control' %>
                    <button type="submit" class="btn btn-fill">Subscribe Now!<i class="icon icons8-advance" id="form-submit"></i></button>
                  </div>
                <% end %>

                <% flash.each do |key, value| %>
                  <div class="alert alert-<%= key %>"><%= value %></div>
                <% end %>

            </div>
            <div class="col-md-3 col-sm-12 col-xs-12 content-widget uv-contact-details-1">
                <div class="widget-title">
                    <h4>Contact Details</h4>
                    <hr class="uv-hr">
                </div>
                <div class="contact-list">
                    <ul class="contact-details">
                      <li><i class="fa fa-link"></i> <a href="elitesketch.com">elitesketch.com</a></li>
                      <li><i class="fa fa-envelope"></i> <a href="mailto:info@yoursite.com">e37@elitesketch.com</a></li>
                      <li><i class="fa fa-phone"></i>+254 703 103579</li>
                      <li><i class="fa fa-home"></i>EliteSketch P.O.Box 1231 - 00232</li>
                    </ul>
                </div>
            </div>
        </div>
    </div>
</section>

app/views/subscriptions/new.html.erb
<h1>New Subscription</h1>

<%= render 'form', subscription: @subscription %>

<%= link_to 'Back', subscriptions_path %>

app/views/subscriptions/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Email:</strong>
  <%= @subscription.email %>
</p>

<%= link_to 'Edit', edit_subscription_path(@subscription) %> |
<%= link_to 'Back', subscriptions_path %>