config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  resources :subscriptions
  devise_for :admin_users, ActiveAdmin::Devise.config
  ActiveAdmin.routes(self)
  devise_for :users
  resources :blogs
  resources :abouts
  resources :contacts
  resources :internships
  resources :organisations
  resources :homes

  root 'homes#index'
end

app/models/internship.rb
# frozen_string_literal: true

class Internship < ApplicationRecord
  belongs_to :organisation

  validates :category, presence: true
  validates :title, presence: true, length: { minimum: 5 }
  validates :body, presence: true
  validates :url, presence: true

  has_attached_file :image, styles: { medium: '300x300>', thumb: '100x100>' }
  validates_attachment_content_type :image, content_type: %r{\Aimage/.*\z}
end

app/controllers/internships_controller.rb
# frozen_string_literal: true

class InternshipsController < ApplicationController
  before_action :set_internship, only: %i[show edit update destroy]

  def index
    @pagy, @internships = pagy(Internship.all.order('created_at DESC'), items: 4)
    @search = params['search']

    if @search.present?
      @category = @search['category']
      @internships = Internship.where('category ILIKE ?', "%#{@category}%")
    end
  end

  def show
    @internship = Internship.find(params[:id])
    @internships = Internship.order('created_at desc').limit(4).offset(1)
  end

  def new
    @internship = Internship.new
  end

  def edit; end

  def create
    @internship = Internship.new(internship_params)

    respond_to do |format|
      if @internship.save
        format.html { redirect_to @internship, notice: 'Internship was successfully created.' }
        format.json { render :show, status: :created, location: @internship }
      else
        format.html { render :new }
        format.json { render json: @internship.errors, status: :unprocessable_entity }
      end
    end
  end

  def update
    respond_to do |format|
      if @internship.update(internship_params)
        format.html { redirect_to @internship, notice: 'Internship was successfully updated.' }
        format.json { render :show, status: :ok, location: @internship }
      else
        format.html { render :edit }
        format.json { render json: @internship.errors, status: :unprocessable_entity }
      end
    end
  end

  def destroy
    @internship.destroy
    respond_to do |format|
      format.html { redirect_to internships_url, notice: 'Internship was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private

  def set_internship
    @internship = Internship.find(params[:id])
  end

  def internship_params
    params.require(:internship).permit(:category, :title, :body, :url, :organisation_id)
  end
end

app/helpers/internships_helper.rb
# frozen_string_literal: true

module InternshipsHelper
end

app/views/internships/_form.html.erb
<%= form_with(model: internship, local: true) do |form| %>
  <% if internship.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(internship.errors.count, "error") %> prohibited this internship from being saved:</h2>

      <ul>
      <% internship.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :category %>
    <%= form.text_field :category %>
  </div>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title %>
  </div>

  <div class="field">
    <%= form.label :body %>
    <%= form.text_area :body %>
  </div>

  <div class="field">
    <%= form.label :organisation_id %>
    <%= form.text_field :organisation_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/internships/edit.html.erb
<h1>Editing Internship</h1>

<%= render 'form', internship: @internship %>

<%= link_to 'Show', @internship %> |
<%= link_to 'Back', internships_path %>

app/views/internships/index.html.erb
<!--
|========================
|      Features Section
|========================
-->
<section class="uv-subpage-heading image-bg" style="background-image: url('assets/header-bg-1.jpg');">
    <div class="overlay">
        <div class="container">
            <div class="row">
                <div class="uv-subhead-content center">
                  <h2>Internships</h2>
                  <span><%= Time.now %></span>
                </div>
            </div>
        </div>
    </div>
</section>
<div class="uv-pagination">
  <div class="container">
    <ul>
      <li><a href="">Home</a></li>
      <li><a href="">Internships</a></li>
    </ul>
  </div>
</div>


<div class="uv-single-contest uv-course-details">
    <div class="container">
        <div class="educationpress-main-content-inner row">
            <aside class="uv-sidebar col-md-3 col-sm-12">
              <div class="uv_aside_hdg default_width mb30">
                <%= simple_form_for :search, url: internships_path, method: "GET", html: { class: 'form-inline' } do |f| %>
                  <h6>Find Internships</h6>
                  <i class="fa fa-minus"></i>
                  <form lpformnum="1">
                    <div class="uv_aside_field">
                      <%= f.input :category, placeholder: "Search by key word here...", input_html: {value: ""} %>
                    </div>
                    <div class="uv_aside_field">
                      <%= f.submit "Search", class: "btn btn-fill btn-block" %>
                    </div>
                  </form>
                <% end %>
              </div>

                <div class="uv-widget">
                  <div class="widget-title">
                    <h4>Subscribe Us</h4>
                    <hr>
                  </div>
                  <div class="uv-newsletter">
                    <p>Subscribe to our weekly Newsletter and stay up to date.</p>
                    <form lpformnum="3" _lpchecked="1">
                      <a href="subscriptions"><i class="btn btn-fill btn-block">Subscribe Now!</i></a>
                    </form>
                  </div>
                </div>

            </aside>
            
            <div id="primary" class="content-area uv-course-listing-inner col-md-9 col-sm-12">
                <div class="uv-sudent-profile-info padding-top-o">
                  <div class="uv-student-courses-overview">
                    <ul>
                      <li>
                        <% @internships.each do |internship| %>
                          <div class="row">
                            <div class="col-sm-4">
                              <div class="course-feature-img">
                                  <%= link_to internship.image.url do %>
                                    <%= image_tag internship.image.url, class: "img-responsive" %>
                                  <% end %>
                                  <span>Available</span>
                              </div>
                            </div>
                            <div class="col-sm-8">
                              <div id="integration-list-2" class="uv-accordinaton">
                                <a class="uv-accordinaton-list">
                                <div class="uv-right-arrow">+</div>
                                  <h6><u><%= internship.category %></u></h6>
                                  <h5><%= internship.title %></h5>
                                  <div class="uv-std-course-info">
                                    <span><b>Posted On:<%= internship.created_at %></b></span>
                                  </div>
                                  <i><b>(Show More/Less)</b></i>
                                </a>
                                <div class="uv-accordition-detail">
                                  <p><%= internship.body %></p>
                                  <a href="<%= internship.url %>" class="btn btn-fill">Apply!</a>
                                </div>
                              </div>
                            </div>
                          </div>
                        <% end %>
                      </li>                                                          
                    </ul>
                  </div>
                </div>
                
              <div class="uv_pagination_outer_wrap">
                <ul>
                  <i><%= pagy_bootstrap_nav(@pagy).html_safe %></i>
                </ul>
              </div>
            </div>
        </div>
    </div>
</div>

<section class="uv-our-clients">
  <div class="container">
    <div class="row section-separator">
      <div class="col-xs-12 center section-title">
        <h2>Our Clients</h2>
      </div>
      <div class="clients-logos">
        <div class="col-md-2 col-sm-4">
          <i class='fas fa-laptop' style='font-size:80px;color:darkblue'><h5>Software Companies</h5></i>
        </div>
        <div class="col-md-2 col-sm-4">
          <i class='fas fa-hotel' style='font-size:80px;color:darkgreen'><h5>Hotels & Restaurant</h5></i>
        </div>
        <div class="col-md-2 col-sm-4">
          <i class='fas fa-school' style='font-size:80px;color:grey'><h5>Schools</h5></i>
        </div>
        <div class="col-md-2 col-sm-4">
          <i class='fas fa-hospital' style='font-size:80px;color:purple'><h5>Hospitals</h5></i>
        </div>
        <div class="col-md-2 col-sm-4">
          <i class='fas fa-satellite-dish' style='font-size:80px;color:maroon'><h5>Media Stations</h5></i>
        </div>
        <div class="col-md-2 col-sm-4">
          <i class='fas fa-sim-card' style='font-size:80px;color:indigo'><h5>Telecommunication Companies</h5></i>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/internships/new.html.erb
<h1>New Internship</h1>

<%= render 'form', internship: @internship %>

<%= link_to 'Back', internships_path %>

app/views/internships/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Category:</strong>
  <%= @internship.category %>
</p>

<p>
  <strong>Title:</strong>
  <%= @internship.title %>
</p>

<p>
  <strong>Body:</strong>
  <%= @internship.body %>
</p>

<p>
  <strong>Organisation:</strong>
  <%= @internship.organisation %>
</p>

<%= link_to 'Edit', edit_internship_path(@internship) %> |
<%= link_to 'Back', internships_path %>